blog/urls.py
# Utworzenie pliku urls.py dla każdej aplikacji jest najlepszym sposobem zapewnienia możliwości wielokrot-
# nego użycia tej aplikacji w innych projektach.

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	# Widoki posta
	path('', 
		 views.post_list, 
		 name = 'post_list'),
	# path('', views.PostListView.as_view(), name='post_list'),
	path('tag/<slug:tag_slug>/',
		 views.post_list, 
		 name='post_list_by_tag'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>/',
		  views.post_detail,
		  name = 'post_detail'),
	path('<int:post_id>/share/', 
		 views.post_share, 
		 name='post_share'),
]


# Do przechwytywania wartości z adresu URL używamy nawiasów trójkątnych. Każda wartość
# określona we wzorcu adresu URL jako <parametr> jest przechwytywana jako ciąg znaków.
# Używamy konwerterów ścieżek, np. <int: year> , aby dokładnie dopasować i zwrócić liczbę
# całkowitą, oraz <slug: post> , by dokładnie dopasować do slugu (ciąg składający się z liter lub
# cyfr ASCII oraz znaków łącznika i podkreślenia). Z wszystkimi konwerterami ścieżek dostarczo-
# nymi z frameworkiem Django można zapoznać się na stronie https://docs.djangoproject.
# com/en/2.0/topics/http/urls/#path-converters.

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Administration page'
admin.site.site_title = 'SiteTitle admin'
admin.site.index_title = 'Zarządzaj zawartością strony'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
	# Nowy wzorzec adresu URL zdefiniowany za pomocą include odnosi się do wzorców adresów
	# URL zdefiniowanych w aplikacji blog , dlatego zostały dołączone w ścieżce blog/ . Te wzorce
	# dołączamy w ramach przestrzeni nazw blog . Przestrzenie nazw muszą być unikatowe w całym
	# projekcie. Później możemy łatwo odwoływać się do adresów URL naszego bloga za pomocą
	# przestrzeni nazw. Adres URL może przyjąć np. format blog: post_list lub blog:post_detail .
	# Więcej informacji na temat przestrzeni nazw URL można znaleźć pod adresem https://docs.
	# djangoproject.com/en/2.0/topics/http/urls/#urlnamespaces.
]

blog/models.py
# models.py: modele danych aplikacji — plik models.py musi znajdować się we
# wszystkich aplikacjach Django, choć może pozostać pusty.

# Model
# to klasa Pythona, która jest podklasą klasy django.db.models.Model . Każdy atrybut tej klasy 
# reprezentuje pole bazy danych. Django tworzy tabelę dla każdego modelu zdefiniowanego w pliku
# models.py. Kiedy definiujesz model, Django udostępnia praktyczny interfejs API do łatwego
# odpytywania obiektów w bazie danych.


# Wszystkie typy pól 
# można znaleźć pod adresem https://docs.djangoproject.com/en/2.0/ref/models/fields/.



from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# from django.core.urlresolvers import reverse
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
   def get_queryset(self):
       return super(PublishedManager,
                   self).get_queryset().filter(status='published')
# Własny manager do QuerySetów klasy Post zwracający tylko opublikowane posty


class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)

	title = models.CharField(max_length = 250)
# 	title : pole reprezentujące tytuł posta. Jest to pole typu CharField , co odpowiada 
# 	kolumnie VARCHAR w bazie danych SQL.

	slug = models.SlugField(max_length = 250,
							unique_for_date = 'publish')
# 	slug : pole przeznaczone do użycia w adresach URL. Jest to krótka etykieta
# 	zawierająca wyłącznie litery, cyfry, znaki podkreślenia lub łączniki. Pola slug
# 	będziemy używać do tworzenia opisowych, przyjaznych dla SEO (ang. Search
# 	Engine Optimization) adresów URL postów na blogu. Dodaliśmy do tego pola
# 	parametr unique_for_date , aby budować adresy URL postów z wykorzystaniem
# 	daty publikacji i pola slug . Django nie dopuści do tego, aby więcej niż jeden post
# 	miał taką samą wartość pola slug dla danej daty.
	
	author = models.ForeignKey(User,
							   on_delete = models.CASCADE,
							   related_name = 'blog_posts')
# 	author : to pole jest kluczem obcym. Definiuje relację wiele do jednego. Informujemy
# 	Django o tym, że każdy post jest napisany przez określonego użytkownika. Natomiast
#	użytkownik może napisać dowolną liczbę postów. Za pomocą tego pola Django
# 	utworzy klucz obcy w bazie danych z wykorzystaniem klucza głównego powiązanego
# 	modelu. W tym przypadku bazujemy na modelu User systemu uwierzytelniania
# 	Django. Parametr on_delete określa zachowanie podczas usuwania obiektu. Nie jest
# 	ono specyficzne dla Django. Jest to zgodne ze standardem SQL. Jeśli wprowadzimy
# 	słowo kluczowe CASCADE , określamy, że po usunięciu użytkownika z bazy danych
# 	zostaną usunięte również powiązane z nim posty na blogu. Wszystkie możliwe
# 	opcje można znaleźć pod adresem https://docs.djangoproject.com/en/2.0/ref/models/
# 	fields/#django.db.models.ForeignKey.on_delete. Za pomocą atrybutu related_name
# 	podajemy nazwę odwróconej relacji — od User do Post . To pozwoli na łatwy dostęp
# 	do powiązanych obiektów.
	
	body = models.TextField()
# 	body : to pole zawiera treść posta. Jest to pole typu CharField , co odpowiada
#	kolumnie TEXT w bazie danych SQL.

	publish = models.DateTimeField(default = timezone.now)
# 	publish : data i godzina opublikowania posta. Wartość domyślna to metoda now
#	obiektu timezone Django. Metoda zwraca bieżącą datę i godzinę w formacie
#	uwzględniającym strefę czasową. Wartość tę można uważać za wersję standardowej
# 	metody Pythona datetime.now z obsługą stref czasowych.

	created = models.DateTimeField(auto_now_add = True)
# 	created : wartość datetime określająca, kiedy utworzono posta. Ponieważ tutaj
# 	używamy opcji auto_now_add , data zostanie zapisana automatycznie podczas
# 	tworzenia obiektu.

	updated = models.DateTimeField(auto_now = True)
# 	updated : data i godzina ostatniej aktualizacji posta. Ponieważ tutaj używamy opcji
#	auto_now , data zostanie zaktualizowana automatycznie podczas zapisywania obiektu.

	status = models.CharField(max_length = 10,
							  choices = STATUS_CHOICES,
							  default = 'draft')
# 	status : pole zawierające status posta. Używamy parametru choices , więc wartość
# 	tego pola można ustawić tylko na jedną z podanych.


	class Meta:
		ordering = ('-publish',)
# 	Klasa Meta wewnątrz modelu zawiera metadane. Informujemy Django, aby po wysłaniu zapyta-
# 	nia do bazy danych wyniki w polu publish były domyślnie sortowane w porządku malejącym.
# 	Wskazanie kolejności malejącej odbywa się poprzez umieszczenie znaku minus przed prefiksem.
# 	W ten sposób posty opublikowane ostatnio będą wyświetlane jako pierwsze.



	def __str__(self):
		return self.title
# 	Metoda __str__() zwraca domyślną, czytelną dla człowieka reprezentację obiektu. Django używa
# 	jej w wielu miejscach, np. w witrynie administracyjnej.


	objects = models.Manager() # Manager domyślny
	published = PublishedManager() # Manager niestandardowy


	def get_absolute_url(self):
		return reverse('blog:post_detail',
						args = [self.publish.year,
						self.publish.strftime('%m'),
						self.publish.strftime('%d'),
						self.slug])
	# Kanoniczne adresy URL dla modeli
	# Przygotowany wcześniej wzorzec adresu URL dla widoku post_detail możemy wykorzystać
	# do budowy kanonicznych adresów URL dla obiektów Post . Konwencja stosowana w Django
	# polega na dodaniu metody get_absolute_url() do modelu zwracającego kanoniczny adres
	# URL obiektu. W przypadku wymienionej metody wykorzystamy metodę reverse() pozwalającą
	# na utworzenie adresu URL na podstawie nazwy i przekazanie parametrów opcjonalnych.
	# Przeprowadź edycję pliku models.py i umieść w nim wiersze, które w poniższym fragmencie
	# kodu zostały pogrubione.
	# Metodę get_absolute_url() będziemy wykorzystywać w naszych szablonach.

	tags = TaggableManager()


class Comment(models.Model):
	post = models.ForeignKey(Post,
							 on_delete = models.CASCADE,
							 related_name = 'comments')
	# Jest to nasz model Comment . Zawiera klucz zewnętrzny ( ForeignKey ) służący 
	# do połączenia komentarza z odpowiednim postem. W modelu została zdefiniowana 
	# relacja typu „wiele do jednego”, ponieważ każdy komentarz jest przeznaczony 
	# dla jednego konkretnego posta, a sam post może mieć wiele komentarzy. 
	# Atrybut related_name umożliwia nadanie nazwy atrybutowi, którego używamy 
	# do obsługi związku między dwoma obiektami. Po zdefiniowaniu wymienionych
	# aspektów możemy za pomocą comment.post() pobrać obiekt komentarza lub też 
	# użyć post.comments.all() do pobrania wszystkich komentarzy dla danego posta. 
	# Jeśli nie zdefiniujesz atrybutu related_name , Django użyje zapisanej małymi 
	# literami nazwy modelu wraz z przyrostkiem _set (w omawianym przykładzie to 
	# będzie comment_set ) jako menedżera obiektu powiązanego z bieżącym.

	# Więcej informacji na temat relacji typu „wiele do jednego” znajdziesz na 
	# stronie https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_one/.

	name = models.CharField(max_length = 80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	active = models.BooleanField(default = True)
	# Zdecydowaliśmy się na dołączenie boolowskiego pola active pozwalającego 
	# na ręczne ukrycie nieodpowiedniego komentarza.

	class Meta:
		ordering = ('created',)

		def __str__(self):
			return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

blog/forms.py
# Django dostarcza dwie klasy bazowe przeznaczone do tworzenia formularzy.
# 	- Form - 	  Klasa jest przeznaczona do budowania formularzy standardowych.
# 	- ModelForm - Klasa jest przeznaczona do budowania formularzy, za pomocą których
# 				  będą tworzone lub uaktualniane egzemplarze modelu.

from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length = 25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required = False,
							    widget = forms.Textarea)
	# W polu comments użyliśmy widżetu Textarea do wyświetlania go jako elementu HTML 
	# <textarea> zamiast jako domyślnego elementu <input>.

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

blog/views.py
# views.py: w tym pliku znajduje się logika aplikacji. Każdy widok otrzymuje
# żądanie HTTP, przetwarza je i zwraca odpowiedź.

from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])

	paginator = Paginator(object_list, 3) # Trzy posty na każdej stronie.
	page = request.GET.get('page')

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# Jeżeli zmienna page nie jest liczbą całkowitą, wówczas pobierana jest pierwsza strona wyników.
		posts = paginator.page(1)
	except EmptyPage:
		# Jeżeli zmienna page ma wartość większą niż numer ostatniej strony wyników, wtedy pobierana
		# jest ostatnia strona wyników.
		posts = paginator.page(paginator.num_pages)

	return render(request, 'blog/post/list.html', {'page': page,
												   'posts': posts,
												   'tag': tag})

class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	# 	Dla wyników zapytania używamy zmiennej kontekstu posts. Wartością domyślną
	# 	będzie object_list, jeśli nie zostanie podana żadna wartość context_object_name 
	paginate_by = 2
	template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug = post,
								   status = 'published',
								   publish__year = year,
								   publish__month = month,
								   publish__day = day)

	# Lista aktywnych komentarzy dla danego posta.
	comments = post.comments.filter(active=True)
	# Budowę kolekcji QuerySet zaczynamy od obiektu post. Wykorzystujemy menedżera 
	# powiązanych obiektów zdefiniowanego jako comments, używając atrybutu related_name 
	# związku w modelu Comment.

	if request.method == 'POST':
		# Komentarz został opublikowany.
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Utworzenie obiektu Comment, ale jeszcze nie zapisujemy go w bazie danych.
			new_comment = comment_form.save(commit=False)
			# Przypisanie komentarza do bieżącego posta.
			new_comment.post = post
			# Zapisanie komentarza w bazie danych.
			new_comment.save()
	else:
		comment_form = CommentForm()

	# Lista podobnych postów.
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

	return render(request,
				  'blog/post/detail.html',
				  {'post': post,
				  'comments': comments,
				  'comment_form': comment_form,
				  'similar_posts': similar_posts})


def post_share(request, post_id):
	# Pobranie posta na podstawie jego identyfikatora.
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	to = ''

	if request.method == 'POST':
		# Formularz został wysłany.
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Weryfikacja pól formularza zakończyła się powodzeniem...
			cd = form.cleaned_data
			# ... więc można wysłać wiadomość e-mail.

			post_url = request.build_absolute_uri(post.get_absolute_url())
			# Ponieważ w wiadomości e-mail trzeba umieścić łącze do posta, bezwzględną 
			# ścieżkę dostępu posta pobieramy za pomocą metody get_absolute_url(). 
			# Następnie tej ścieżki dostępu używamy jako danych wejściowych dla metody 
			# request.build_absolute_uri() i budujemy kompletny adres URL zawierający 
			# schemat HTTP oraz nazwę hosta.

			subject = '{} ({}) zachęca do przeczytania "{}"'.format(cd['name'], 
																	cd['email'], 
																	post.title)
			message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez {}: {}'.format(post.title, 
																									post_url, 
																									cd['name'], 
																									cd['comments'])
			send_mail(subject, message, 'admin@myblog.com', [cd['to']])
			sent = True
			to = cd['to']
	else:
		form = EmailPostForm()

	return render(request, 'blog/post/share.html', {'post': post,
													'form': form,
													'to' : to,
													'sent': sent})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<h1>{{ post.title }}</h1>
	<p class="date">
		Opublikowany {{ post.publish }} przez {{ post.author }}
	</p>

	{% if post.tags.all %}
		<p class="tags">
			Tagi: 
			{% for tag in post.tags.all %}
				<a href="{% url "blog:post_list_by_tag" tag.slug %}">
					{{ tag.name }}
				</a>
				{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>
	{% endif %}

	{{ post.body|linebreaks }}

	<p>
		<a href="{% url "blog:post_share" post.id %}">
			Udostępnij post
		</a>
	</p>

	<h2>Podobne posty</h2>
	{% for post in similar_posts %}
		<p>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</p>
	{% empty %}
		Nie ma podobnych postów.
	{% endfor %}

	{% with comments.count as total_comments %}
		<h2>
			{{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
			{% comment %}
				Działanie filtru szablonu o nazwie pluralize polega na wyświetleniu y, jeśli wartość jest inna niż 1 . Dlatego też poprzedzający filtr tekst zostanie wyświetlony w postaci 0 komentarzy, 1 komentarz, N komentarzy.
			{% endcomment %}
		</h2>
	{% endwith %}
	{% comment %}
		Znacznik {% with %} szablonu okazuje się użyteczny, gdy chcemy uniknąć wykonania zapytania do bazy danych lub wielokrotnego uzyskania dostępu do kosztownych metod.
	{% endcomment %}

	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p>Nie ma jeszcze żadnych komentarzy.</p>
	{% endfor %}

	{% if new_Comment %}
		<h2>Twój komentarz został dodany.</h2>
	{% else %}
		<h2>Dodaj nowy komentarz</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Dodaj komentarz"></p>
		</form>
	{% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój blog{% endblock %}

{% block content %}
	<h1>Mój blog</h1>

	{% if tag %}
		<h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
	{% endif %}

	{% for post in posts %}

		{% comment %}
			Tytuł posta jest łączem w postaci kanonicznego adresu URL posta.
		{% endcomment %}
		<h2>
			<a href="{{ post.get_absolute_url }}">
				{{ post.title }}
			</a>
		</h2>

		{% if post.tags.all %}
			<p class="tags">
				Tagi: 
				{% for tag in post.tags.all %}
					<a href="{% url "blog:post_list_by_tag" tag.slug %}">
						{{ tag.name }}
					</a>
					{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</p>
		{% endif %}

		<p class="date">
			Opublikowany {{ post.publish }} przez {{ post.author }}
		</p>
		{{ post.body|truncatewords:30|linebreaks }}
		{% comment %}
			W treści posta stosowane są dwa filtry szablonu. Pierwszy, truncatewords , powoduje ograniczenie treści do podanej liczby słów. Natomiast drugi, linebreaks, konwertuje dane wyjściowe na postać kodu HTML wraz z odpowiednimi znakami nowego wiersza. Istnieje możliwość wykorzystania dowolnej liczby filtrów szablonu, a każdy z nich będzie zastosowany względem danych wyjściowych wygenerowanych przez poprzedni.
		{% endcomment %}
	{% endfor %}
	
	{% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
	{% if sent %}
		<h1>Wiadomość e-mail została wysłana</h1>
		<p>
			Wysłanie posta <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a> do {{ to }} zakończyło się sukcesem.
		</p>
	{% else %}
		<h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
		<form action="." method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Wyślij wiadomość e-mail">
		</form>
	{% endif %}
{% endblock %}